### ISSUE TITLE
Comment on async/await

### ISSUE THREAD

**Issue by mathieudutour** [zcallan/sketch-bacon-ipsum#1]
This is not an issue but more a comment about your readme:

> Since this plugin uses async/await, please make sure your version of Node is up to date.

A plugin doesn't run in NodeJS, it is compiled (with webpack/babel) and run in an environment similar to Safari.

**Comment by zcallan** [comment]
Oh that's great! I had a look at the compiled JS code and noticed the async/await remained after compilation (and therefore clearly wasn't ES5).

Thanks for the heads up, I'll remove it from the readme :)

**Comment by mathieudutour** [comment]
oh wait, if it's not compiled away, then it will depend on the macOS version (10.13 supports async/await but I'm not sure about previous versions). You can change the babel config to compile it away tho

**Comment by zcallan** [comment]
Compiled `async` to generators via the ES7 babel plugin - should be sweet now!

Cheers Mathieu :)
